CLIENTS = {
    'http://www.adium.im/': ['adium.png', 'Adium'],
    'http://www.adiumx.com/caps': ['adium.png', 'Adium'],
    'http://www.adiumx.com': ['adium.png', 'Adium'],
    'http://aqq.eu/': ['aqq.png', 'Aqq'],
    'http://www.asterisk.org/xmpp/client/caps': ['asterisk.png', 'Asterisk'],
    'http://ayttm.souceforge.net/caps': ['ayttm.png', 'Ayttm'],
    'http://www.barobin.com/caps': ['bayanicq.png', 'Bayanicq'],
    'http://bitlbee.org/xmpp/caps': ['bitlbee.png', 'Bitlbee'],
    'http://simpleapps.ru/caps#blacksmith': ['bot.png', 'Blacksmith'],
    'http://blacksmith-2.googlecode.com/svn/': ['bot.png', 'Blacksmith-2'],
    'http://jabber.pdg.pl/caps': ['bombus-klub.png', 'Bombus-klub'],
    'http://klub54.wen.ru': ['bombus-klub.png', 'Bombus-klub'],
    'http://bombus-im.org/java': ['bombus.png', 'Bombus'],
    'http://bombusmod.net.ru/caps': ['bombusmod.png', 'Bombusmod'],
    'http://bombusng-md.googlecode.com': ['bombusng.png', 'Bombus-NG'],
    'http://bombus-im.org/ng': ['bombusng.png', 'Bombus-NG'],
    'http://voffk.org.ru/bombus': ['bombusplus.png', 'Bombus+'],
    'http://bombusng-qd.googlecode.com': ['bombusqd.png', 'Bombus-NG'],
    'http://bombusmod-qd.wen.ru/caps': ['bombusqd.png', 'BombusQD'],
    'http://bombusmod.net.ru': ['bombusmod.png', 'Bombusmod'],
    'http://ex-im.name/caps': ['bombusmod.png', 'Bombusmod'],
    'http://bombusmod.eu,http://bombus.pl': ['bombuspl.png', 'Bombusmod'],
    'ChatSecure': ['chatsecure.png', 'ChatSecure'],
    'http://coccinella.sourceforge.net/protocol/caps': \
        ['coccinella.png', 'Coccinella'],
    'http://conversations.im': ['conversations.png', 'Conversations'],
    'Conversations Legacy': ['conversations-legacy.png', 'Conversations Legacy'],
    'http://digsby.com/caps': ['digsby.png', 'Digsby'],
    'https://dino.im': ['dino.png', 'Dino'],
    'http://emess.eqx.su/caps': ['emess.png', 'Emess'],
    'http://live.gnome.org/empathy/caps': \
        ['telepathy.freedesktop.org.png', 'Empathy'],
    'http://eqo.com/': ['libpurple.png', 'Eqo'],
    'http://exodus.jabberstudio.org/caps': ['exodus.png', 'Exodus'],
    'http://fatal-bot.spb.ru/caps': ['bot.png', 'Fatal-bot'],
    'http://svn.posix.ru/fatal-bot/trunk': ['bot.png', 'Fatal-bot'],
    'http://isida.googlecode.com': ['isida-bot.png', 'Isida'],
    'http://isida-bot.com': ['isida-bot.png', 'Isida'],
    'facebook.com': ['facebook.png', 'Facebook'],
    'http://jabga.ru': ['fin.png', 'Fin jabber'],
    'http://chat.freize.org/caps': ['freize.png', 'Freize'],
    'http://gabber.sourceforge.net': ['gabber.png', 'Gabber'],
    'http://gaim.sf.net/caps': ['gaim.png', 'Gaim'],
    'http://gajim.org': ['gajim.png', 'Gajim'],
    'http://gajim.org/caps': ['gajim.png', 'Gajim'],
    'http://glu.net/': ['glu.png', 'Glu'],
    'http://mail.google.com/xmpp/client/caps': ['google.com.png', 'GMail'],
    'http://www.android.com/gtalk/client/caps': \
        ['talk.google.com.png', 'GTalk'],
    'talk.google.com': ['talk.google.com.png', 'GTalk'],
    'http://talkgadget.google.com/client/caps': ['google.png', 'GTalk'],
    'http://talk.google.com/xmpp/bot/caps': ['google.png', 'GTalk'],
    'http://aspro.users.ru/historian-bot/': ['bot.png', 'Historian-bot'],
    'http://www.apple.com/ichat/caps': ['ichat.png', 'IChat'],
    'http://instantbird.com/': ['instantbird.png', 'Instantbird'],
    'http://j-tmb.ru/caps': ['bot.png', 'J-tmb'],
    'http://jabbroid.akuz.de': ['android.png', 'Jabbroid'],
    'http://jabbroid.akuz.de/caps': ['android.png', 'Jabbroid'],
    'http://dev.jabbim.cz/jabbim/caps': ['jabbim.png', 'Jabbim'],
    'http://jabbrik.ru/caps': ['bot.png', 'Jabbrik'],
    'http://jabrvista.net.ru': ['bot.png', 'Jabvista'],
    'http://jajc.jrudevels.org/caps': ['jajc.png', 'JAJC'],
    'http://qabber.ru/jame-bot': ['bot.png', 'Jame-bot'],
    'https://www.jappix.com/': ['jappix.png', 'Jappix'],
    'http://japyt.googlecode.com': ['japyt.png', 'Japyt'],
    'http://jasmineicq.ru/caps': ['jasmine.png', 'Jasmine'],
    'http://jimm.net.ru/caps': ['jimm-aspro.png', 'Jimm'],
    'http://jitsi.org' :['jitsi.png', 'Jitsi'],
    'http://jtalk.ustyugov.net/caps': ['jtalk.png', 'Jtalk'],
    'http://pjc.googlecode.com/caps': ['jubo.png', 'Jubo'],
    'http://juick.com/caps': ['juick.png', 'Juick'],
    'http://kopete.kde.org/jabber/caps': ['kopete.png', 'Kopete'],
    'http://bluendo.com/protocol/caps': ['lampiro.png', 'Lampiro'],
    'libpurple': ['libpurple.png', 'Libpurple'],
    'http://lytgeygen.ru/caps': ['bot.png', 'Lytgeygen'],
    'http://agent.mail.ru/caps': ['mailruagent.png', 'Mailruagent'],
    'http://agent.mail.ru/': ['mailruagent.png', 'Mailruagent'],
    'http://tomclaw.com/mandarin_im/caps': ['mandarin.png', 'Mandarin'],
    'http://mcabber.lilotux.net/caps': ['mcabber.png', 'MCabber'],
    'http://mcabber.com/caps': ['mcabber.png', 'MCabber'],
    'http://mchat.mgslab.com/': ['mchat.png', 'Mchat'],
    'https://www.meebo.com/': ['meebo.png', 'Meebo'],
    'http://megafonvolga.ru/': ['megafon.png', 'Megafon'],
    'http://miranda-im.org/caps': ['miranda.png', 'Miranda'],
    'http://miranda-ng.org/caps' :['miranda_ng.png', 'Miranda NG'],
    'nimbuzz:caps': ['nimbuzz.png', 'Nimbuzz'],
    'http://nimbuzz.com/caps': ['nimbuzz.png', 'Nimbuzz'],
    'http://home.gna.org/': ['omnipresence.png', 'Omnipresence'],
    'http://oneteam.im/caps': ['oneteamiphone.png', 'OneTeam'],
    'http://www.process-one.net/en/solutions/oneteam_iphone/': \
        ['oneteamiphone.png', 'OneTeam-iphone'],
    'rss@isida-bot.com': ['osiris.png', 'Osiris'],
    'http://chat.ovi.com/caps': ['ovi-chat.png', 'Ovi-chat'],
    'http://opensource.palm.com/packages.html': ['palm.png', 'Palm'],
    'http://palringo.com/caps': ['palringo.png', 'Palringo'],
    'http://pandion.im/': ['pandion.png', 'Pandion'],
    'http://pidgin.im/': ['pidgin.png', 'Pidgin'],
    'http://pidgin.im/caps': ['pidgin.png', 'Pidgin'],
    'http://pigeon.vpro.ru/caps': ['pigeon.png', 'Pigeon'],
    'Pix-Art Messenger': ['pixart.png', 'Pix-Art Messenger'],
    'httр://sleekxmpp.com/ver/1.1.11': ['poezio.png', 'Poezio'],
    'http://psi-im.org/caps': ['psi.png', 'Psi'],
    'http://psi-plus.com': ['psiplus.png', 'Psi+'],
    'http://psi-dev.googlecode.com/caps': ['psiplus.png', 'Psi+'],
    'psto@psto.net': ['psto.png', 'Psto'],
    'http://pyaim': ['pyaim-t.png', 'PyAIM-t'],
    'http://pyicq': ['pyicq-t.png', 'PyICQ-t'],
    'http://spectrum.im/transport': ['pyicq-t.png', 'PyICQ-t'],
    'http://qq-im.com/caps': ['qq.png', 'QQ'],
    'http://qq.com/caps': ['qq.png', 'QQ'],
    'http://2010.qip.ru/caps': ['qip.png', 'Qip'],
    'http://qip.ru/caps': ['qip.png', 'Qip'],
    'http://qip.ru/caps?QIP': ['qip.png', 'Qip'],
    'http://pda.qip.ru/caps': ['qippda.png', 'Qip-PDA'],
    'http://qutim.org': ['qutim.png', 'QutIM'],
    'http://qutim.org/': ['qutim.png', 'QutIM'],
    'http://apps.radio-t.com/caps': ['radio-t.png', 'Radio-t'],
    'Siemens': ['siejc.png', 'Siemens'],  # Siemens Native Jabber Client
    'http://sim-im.org/caps': ['sim.png', 'Sim'],
    'http://www.lonelycatgames.com/slick/caps': ['slick.png', 'Slick'],
    'http://slixmpp.com/ver/1.2.4': ['bot.png', 'Slixmpp'],
    'http://slixmpp.com/ver/1.3.0': ['bot.png', 'Slixmpp'],
    'http://snapi-bot.googlecode.com/caps': ['bot.png', 'Snapi-bot'],
    'http://www.igniterealtime.org/project/spark/caps': ['spark.png', 'Spark'],
    'http://spectrum.im/': ['spectrum.png', 'Spectrum'],
    'http://storm-bot.googlecode.com/svn/trunk': ['bot.png', 'Storm-bot'],
    'http://swift.im': ['swift.png', 'Swift'],
    'http://jabber-net.ru/caps/talisman-bot': ['bot.png', 'Talisman-bot'],
    'http://jabber-net.ru/talisman-bot/caps': ['bot.png', 'Talisman-bot'],
    'http://www.google.com/xmpp/client/caps': ['talkonaut.png', 'Talkonaut'],
    'telepathy.': ['telepathy.freedesktop.org.png', 'Telepathy'],
    'http://telepathy.freedesktop.org/caps': \
        ['telepathy.freedesktop.org.png', 'Telepathy'],
    'http://tigase.org/messenger': ['tigase.png', 'Tigase'],
    'http://tkabber.jabber.ru/': ['tkabber.png', 'Tkabber'],
    'http://trillian.im/caps': ['trillian.png', 'Trillian'],
    'http://vacuum-im.googlecode.com': ['vacuum.png', 'Vacuum'],
    'http://code.google.com/p/vacuum-im/': ['vacuum.png', 'Vacuum'],
    'vk.com': ['vkontakte.png', 'Vkontakte'],
    'http://pyvk-t.googlecode.com/caps': ['vkontakte.png', 'Vkontakte'],
    'http://pyvk': ['vkontakte.png', 'Vkontakte'],
    'http://witcher-team.ucoz.ru/': ['bot.png', 'Witcher'],
    'http://online.yandex.ru/caps': ['yaonline.png', 'Yaonline'],
    'http://www.igniterealtime.org/projects/smack/': ['xabber.png', 'Xabber'],
    'http://www.xfire.com/': ['xfire.png', 'Xfire'],
    'http://www.xfire.com/caps': ['xfire.png', 'Xfire'],
    'http://xu-6.jabbrik.ru/caps': ['bot.png', 'XU-6'],
}
LIBPURPLE_CLIENTS = {
    'adium': 'http://www.adium.im/',
    'eqo': 'http://eqo.com/',
    'finch': 'http://pidgin.im/',
    'instantbird': 'http://instantbird.com/',
    'meebo': 'https://www.meebo.com/',
    'palm': 'http://opensource.palm.com/packages.html',
    'pidgin': 'http://pidgin.im/',
    'spectrum': 'http://spectrum.im/',
    'telepathy-haze': 'http://pidgin.im/'
}