DEFAULT_DATA = {
    ":)": "🙂",
    ":D": "😄",
    ";)": "😉",
    "afaik": "as far as I know",
    "afair": "as far as I can remember",
    "afaict": "as far as I can tell",
    "afk": "away from keyboard",
    "asap": "as soon as possible",
    "atm": "at the moment",
    "bbiab": "be back in a bit",
    "bbiaf": "be back in a few (minutes)",
    "bbl": "be back later",
    "bbs": "be back soon",
    "b/c": "because",
    "bf": "boyfriend",
    "bfo": "blinding flash of the obvious",
    "brb": "be right back",
    "bsod": "blue screen of death",
    "btw": "by the way",
    "ciao": "Italian for goodbye",
    "ctrn": "can't talk right now",
    "cul8r": "see you later",
    "cya": "see ya",
    "dhtb": "don't have the bandwidth",
    "dm": "direct message",
    "f2f": "face to face",
    "fubar": "fucked up beyond all recognition",
    "fwiw": "for what it's worth",
    "fyi": "for your information",
    "<g>": "grin",
    "*g*": "grin",
    "gf": "girlfriend",
    "gmta": "great minds think alike",
    "g2g": "got to go",
    "iam": "in a meeting",
    "ianal": "I am not a lawyer",
    "idk": "I don't know",
    "ihmb": "I hate my boss",
    "iirc": "if I recall correctly",
    "imho": "in my humble opinion",
    "imo": "in my opinion",
    "iow": "in other words",
    "irl": "in real life",
    "jid": "jabber identifier",
    "j/k": "just kidding",
    "lmao": "laughing my ass off",
    "ok": "okay",
    "lol": "laugh out loud",
    "l8r": "later",
    "msg": "message",
    "n/m": "nevermind",
    "n/p": "no problem",
    "nvm": "nevermind",
    "oAo": "over and out!",
    "omg": "oh my god",
    "oob": "out of band",
    "op": "original poster",
    "ot": "off topic",
    "otoh": "on the other hand",
    "otp": "on the phone",
    "oww": "oops, wrong window!",
    "pita": "pain in the ass",
    "pm": "private message",
    "pov": "point of view",
    "pw": "password",
    "rotfl": "rolling on the floor laughing",
    "rsn": "real soon now",
    "rtfm": "read the friendly manual",
    "slap": "sounds like a plan",
    "smh": "shaking my head",
    "tbh": "to be honest",
    "thx": "thanks",
    "tia": "thanks in advance",
    "til": "today I learned",
    "tldr": "too long, didn't read",
    "tla": "three-letter arconym",
    "ttfn": "ta ta for now",
    "ttyl": "talk to you later",
    "wb": "welcome back",
    "wfm": "works for me",
    "wtf": "what the fuck?!",
    "wth": "what the hell",
    "wtg": "way to go!",
    "xfer": "transfer",
    "ymmv": "your mileage may vary",
}
